#Include our standard library
include:
  - remote: 'https://raw.githubusercontent.com/pnnl-miscscripts/gitlab-lib/v1/gitlab-lib.yaml'

stages:
- check
- build

variables:
  CONTAINER_VERSION: 1.0.28
  CONTAINER_TAG: $CI_COMMIT_BRANCH-$CONTAINER_VERSION
  KANIKO_EXTRA_ARGS: --git branch=$CI_COMMIT_BRANCH
  GIT_DEPTH: 10

#Check to see if the image already exists and blocks overwriting an existing image. (New image = new tag, never overwrite, is a best practice.)
verify-new-image:
  extends: .pnnllib-gitlab-verify-new-image
  stage: check
  tags:
    - k8s
    - rzr
    - codebuilds

#Build and push the container.
build-image:
  extends: .pnnllib-gitlab-build-container-image
  stage: build
  tags:
    - k8s
    - rzr
    - codebuilds

#Load a secret into the Kubernetes cluster.
deply-token-to-cluster:
  extends: .pnnllib-gitlab-load-deploy-token
  stage: build
  only:
    - master@emslc60117/nmRanalysisApp
  tags:
    - k8s
    - rzr
    - nmranalysis
  variables:
    KUBERNETES_HELPER_MEMORY_REQUEST: 256Mi
    KUBERNETES_HELPER_MEMORY_LIMIT: 256Mi
