version: '3.7' 
services:
    postgresdb:
        restart: always
        image: postgres:latest
        ports:
        - 5432:5432
        env_file:
        - ./db-prod.env

    web: 
        build: .
        image: nmrshinyapp
        container_name: nmrshinyapp
        ports:
            - "3838:3838"
