#' Simultaneously update reference metabolite datatable and plot via proxies
#'
#' @param tabproxy A datatable proxy object. See details.
#' @param pltproxy A plotly proxy object. See details.
#' @param newdat A dataframe. See details.
#'
#' @details This function is responsible for updating the reference metabolite datatable and accompanying plot
#' according to the changes made interactively to each by the user. The datatable proxy object required by
#' tabproxy corresponds to the datatable displaying the reference metabolite fitting information. See
#' ref_data_ROIeditingUI() and ref_data_editingServer() for additional details.
#' The plotly proxy object corresponds to the plotly figured generated by plot_refmet_data(). The dataframe required by
#' newdat should contain all of the fitting parameter information specific to the peak centers of a selected
#' reference metabolite. This dataframe should have the following named columns, in the following order: "ROI left edge (ppm)",
#' "ROI right edge (ppm)", "Quantification Mode", "Metabolite", "Quantification Signal", "Chemical shift(ppm)",
#' "Chemical shift tolerance (ppm)", "Half bandwidth (Hz)", "Multiplicity", "J coupling (Hz)", "Roof effect",
#' "Quantify", "HMDB_code", and "rowid".
#'
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#'
ProxyUpdate_refmet_tabplot <- function(tabproxy, pltproxy, newdat){

  # Line shape update
  ROI_lines <- ROI_line_gen(data = newdat)

  # Annotation update
  ROI_annots <- ROI_annot_gen(data = newdat)

  # Update plot
  plotly::plotlyProxyInvoke(pltproxy, "relayout",
                            list(annotations = ROI_annots,
                                 shapes = ROI_lines))
  # Update table
  newdat <- newdat %>% dplyr::ungroup() %>% dplyr::select(-.data$rowid) %>%
    dplyr::mutate(Signal = paste0(.data$Metabolite, " [", .data$`Quantification Signal`, "]")) %>%
    dplyr::select(.data$Signal, .data$Quantify, .data$`Chemical shift(ppm)`, .data$`Chemical shift tolerance (ppm)`,
                  .data$`Half bandwidth (Hz)`, .data$Multiplicity, .data$`J coupling (Hz)`, .data$`J coupling 2 (Hz)`,
                  .data$`Roof effect`, .data$`Roof effect 2`)

  DT::replaceData(tabproxy, newdat,
                  resetPaging = FALSE,
                  rownames    = FALSE)
}
