#' Simultaneously update reference metabolite datatable and plot via proxies
#'
#' @param tabproxy A datatable proxy object. See details.
#' @param pltproxy A plotly proxy object. See details.
#' @param newdat A dataframe. See details.
#'
#' @details This function is responsible for updating the reference metabolite datatable and accompanying plot
#' according to the changes made interactively to each by the user. The datatable proxy object required by 
#' tabproxy corresponds to the datatable displaying the reference metabolite fitting information. See 
#' ref_data_ROIeditingUI() and ref_data_editingServer() for additional details. 
#' The plotly proxy object corresponds to the plotly figured generated by plot_refmet_data(). The dataframe required by 
#' newdat should contain all of the fitting parameter information specific to the peak centers of a selected
#' reference metabolite. This dataframe should have the following named columns, in the following order: "ROI left edge (ppm)", 
#' "ROI right edge (ppm)", "Quantification Mode", "Metabolite", "Quantification Signal", "Chemical shift(ppm)", 
#' "Chemical shift tolerance (ppm)", "Half bandwidth (Hz)", "Multiplicity", "J coupling (Hz)", "Roof effect", 
#' "Quantify", "HMDB_code", and "rowid".
#' 
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#'
ProxyUpdate_refmet_tabplot <- function(tabproxy, pltproxy, newdat){
  
  # Line shape update
  ROI_lines <- ROI_line_gen(dspedt_refmet_data = newdat)
  
  # Annotation update
  ROI_annots <- ROI_annot_gen(dspedt_refmet_data = newdat)
  
  # Update plot
  plotly::plotlyProxyInvoke(pltproxy, "relayout",
                            list(annotations = ROI_annots,
                                 shapes = ROI_lines))
  # Update table
  DT::replaceData(tabproxy, newdat %>% dplyr::select(-.data$rowid),
                  resetPaging = FALSE, 
                  rownames    = FALSE)
}
