#' rDolphin: save_output
#'
#' @param spectrum_index Index of sample spectrum to be fitted
#' @param signals_codes Signal indices to be fitted
#' @param results_to_save Final results list
#' @param buck_step The difference between two adjacent chemical shift values (i.e. ppm resolution)
#' @param final_output Dataframe for final quantifications
#'
#' @details This function is based on code that was forked directly from rDolphin (https://github.com/danielcanueto/rDolphin/tree/master/R). This function saves
#' the formatted output of the quantification generated by the automatic profiling routine.
#'
save_output <- function(spectrum_index, signals_codes, results_to_save, buck_step, final_output){

  #Created by Daniel Canueto 30/08/2016
  #Save quantification, $chemical_shift, fitting error and signal area ratio.

  final_output$quantification[spectrum_index,signals_codes]    <- results_to_save$quantification
  final_output$fitting_error[spectrum_index,signals_codes]     <- results_to_save$fitting_error
  final_output$signal_area_ratio[spectrum_index,signals_codes] <- results_to_save$signal_area_ratio
  final_output$chemical_shift[spectrum_index,signals_codes]    <- results_to_save$chemical_shift
  final_output$intensity[spectrum_index,signals_codes]         <- results_to_save$intensity
  final_output$half_bandwidth[spectrum_index,signals_codes]    <- results_to_save$half_bandwidth

  return(final_output)

}
